# Generated by Django 4.2.11 on 2024-04-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ligne', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('heure_depart', models.TimeField()),
                ('heure_arrivee', models.TimeField()),
                ('duree_trajet', models.DurationField()),
                ('destination', models.CharField(max_length=100)),
                ('detail_trajet', models.ImageField(blank=True, null=True, upload_to='detail')),
            ],
        ),
    ]
